// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2sYGcG1qUic10ZOkGrXtCkp1QOpgoA0',
    appId: '1:753170767676:android:b7d3fa0809b65e46ae0839',
    messagingSenderId: '753170767676',
    projectId: 'gng2101-personalsafety',
    databaseURL: 'https://gng2101-personalsafety-default-rtdb.firebaseio.com',
    storageBucket: 'gng2101-personalsafety.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtlq7p5Os_tEREPEYt_67PqAed8ZpCpTU',
    appId: '1:753170767676:ios:dcc4412866c25ac3ae0839',
    messagingSenderId: '753170767676',
    projectId: 'gng2101-personalsafety',
    databaseURL: 'https://gng2101-personalsafety-default-rtdb.firebaseio.com',
    storageBucket: 'gng2101-personalsafety.appspot.com',
    iosClientId: '753170767676-tfnvmsc8uea98jeifrg56p2q6788s8ni.apps.googleusercontent.com',
    iosBundleId: 'gng2102.uottawa.personalSafety',
  );
}
